pretrained_base_model_path: '/app/models/misc/Comfyui_MusePose/sd-image-variations-diffusers'
pretrained_vae_path: '/app/models/misc/Comfyui_MusePose/sd-vae-ft-mse'
image_encoder_path: '/app/models/misc/Comfyui_MusePose/image_encoder'



denoising_unet_path: "/app/models/misc/Comfyui_MusePose/MusePose/denoising_unet.pth"
reference_unet_path: "/app/models/misc/Comfyui_MusePose/MusePose/reference_unet.pth"
pose_guider_path: "/app/models/misc/Comfyui_MusePose/MusePose/pose_guider.pth"
motion_module_path: "/app/models/misc/Comfyui_MusePose/MusePose/motion_module.pth"



inference_config: "configs/inference_v2.yaml"
weight_dtype: 'fp16'

